# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .app import *
from .domain import *
from .get_app import *
from .get_domain import *
from .get_secret import *
from .get_service import *
from .provider import *
from .secret import *
from .service import *
from .volume import *
from ._inputs import *
from . import outputs
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "koyeb",
  "mod": "index/app",
  "fqn": "pulumi_koyeb",
  "classes": {
   "koyeb:index/app:App": "App"
  }
 },
 {
  "pkg": "koyeb",
  "mod": "index/domain",
  "fqn": "pulumi_koyeb",
  "classes": {
   "koyeb:index/domain:Domain": "Domain"
  }
 },
 {
  "pkg": "koyeb",
  "mod": "index/secret",
  "fqn": "pulumi_koyeb",
  "classes": {
   "koyeb:index/secret:Secret": "Secret"
  }
 },
 {
  "pkg": "koyeb",
  "mod": "index/service",
  "fqn": "pulumi_koyeb",
  "classes": {
   "koyeb:index/service:Service": "Service"
  }
 },
 {
  "pkg": "koyeb",
  "mod": "index/volume",
  "fqn": "pulumi_koyeb",
  "classes": {
   "koyeb:index/volume:Volume": "Volume"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "koyeb",
  "token": "pulumi:providers:koyeb",
  "fqn": "pulumi_koyeb",
  "class": "Provider"
 }
]
"""
)
