// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package koyeb

import (
	"context"
	"reflect"

	"github.com/koyeb/pulumi-koyeb/sdk/go/koyeb/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/koyeb/pulumi-koyeb/sdk/go/koyeb"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := koyeb.LookupApp(ctx, &koyeb.LookupAppArgs{
//				Name: "my-app",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupApp(ctx *pulumi.Context, args *LookupAppArgs, opts ...pulumi.InvokeOption) (*LookupAppResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAppResult
	err := ctx.Invoke("koyeb:index/getApp:getApp", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApp.
type LookupAppArgs struct {
	// The app name
	Name string `pulumi:"name"`
}

// A collection of values returned by getApp.
type LookupAppResult struct {
	// The date and time of when the app was created
	CreatedAt string `pulumi:"createdAt"`
	// The app domains
	Domains []GetAppDomain `pulumi:"domains"`
	// The app ID
	Id string `pulumi:"id"`
	// The app name
	Name string `pulumi:"name"`
	// The organization ID owning the app
	OrganizationId string `pulumi:"organizationId"`
	// The date and time of when the app was last updated
	UpdatedAt string `pulumi:"updatedAt"`
}

func LookupAppOutput(ctx *pulumi.Context, args LookupAppOutputArgs, opts ...pulumi.InvokeOption) LookupAppResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupAppResultOutput, error) {
			args := v.(LookupAppArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv LookupAppResult
			secret, err := ctx.InvokePackageRaw("koyeb:index/getApp:getApp", args, &rv, "", opts...)
			if err != nil {
				return LookupAppResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupAppResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupAppResultOutput), nil
			}
			return output, nil
		}).(LookupAppResultOutput)
}

// A collection of arguments for invoking getApp.
type LookupAppOutputArgs struct {
	// The app name
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupAppOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAppArgs)(nil)).Elem()
}

// A collection of values returned by getApp.
type LookupAppResultOutput struct{ *pulumi.OutputState }

func (LookupAppResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAppResult)(nil)).Elem()
}

func (o LookupAppResultOutput) ToLookupAppResultOutput() LookupAppResultOutput {
	return o
}

func (o LookupAppResultOutput) ToLookupAppResultOutputWithContext(ctx context.Context) LookupAppResultOutput {
	return o
}

// The date and time of when the app was created
func (o LookupAppResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The app domains
func (o LookupAppResultOutput) Domains() GetAppDomainArrayOutput {
	return o.ApplyT(func(v LookupAppResult) []GetAppDomain { return v.Domains }).(GetAppDomainArrayOutput)
}

// The app ID
func (o LookupAppResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.Id }).(pulumi.StringOutput)
}

// The app name
func (o LookupAppResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.Name }).(pulumi.StringOutput)
}

// The organization ID owning the app
func (o LookupAppResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

// The date and time of when the app was last updated
func (o LookupAppResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAppResultOutput{})
}
