// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Koyeb.Outputs
{

    [OutputType]
    public sealed class GetSecretGithubRegistryResult
    {
        /// <summary>
        /// The registry password
        /// </summary>
        public readonly string Password;
        /// <summary>
        /// The registry username
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private GetSecretGithubRegistryResult(
            string password,

            string username)
        {
            Password = password;
            Username = username;
        }
    }
}
