// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Koyeb.Outputs
{

    [OutputType]
    public sealed class KoyebServiceDefinitionGit
    {
        public readonly string Branch;
        public readonly string? BuildCommand;
        public readonly bool? NoDeployOnPush;
        public readonly string Repository;
        public readonly string? RunCommand;

        [OutputConstructor]
        private KoyebServiceDefinitionGit(
            string branch,

            string? buildCommand,

            bool? noDeployOnPush,

            string repository,

            string? runCommand)
        {
            Branch = branch;
            BuildCommand = buildCommand;
            NoDeployOnPush = noDeployOnPush;
            Repository = repository;
            RunCommand = runCommand;
        }
    }
}
