// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Koyeb.Outputs
{

    [OutputType]
    public sealed class KoyebSecretPrivateRegistry
    {
        public readonly string Password;
        public readonly string Url;
        public readonly string Username;

        [OutputConstructor]
        private KoyebSecretPrivateRegistry(
            string password,

            string url,

            string username)
        {
            Password = password;
            Url = url;
            Username = username;
        }
    }
}
