// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Koyeb.Outputs
{

    [OutputType]
    public sealed class ServiceDefinitionHealthCheck
    {
        /// <summary>
        /// The period in seconds to wait for the instance to become healthy, default is 5s
        /// </summary>
        public readonly int? GracePeriod;
        public readonly Outputs.ServiceDefinitionHealthCheckHttp? Http;
        /// <summary>
        /// The period in seconds between two health checks, default is 60s
        /// </summary>
        public readonly int? Interval;
        /// <summary>
        /// The number of consecutive failures before attempting to restart the service, default is 3
        /// </summary>
        public readonly int? RestartLimit;
        public readonly Outputs.ServiceDefinitionHealthCheckTcp? Tcp;
        /// <summary>
        /// The maximum time to wait in seconds before considering the check as a failure, default is 5s
        /// </summary>
        public readonly int? Timeout;

        [OutputConstructor]
        private ServiceDefinitionHealthCheck(
            int? gracePeriod,

            Outputs.ServiceDefinitionHealthCheckHttp? http,

            int? interval,

            int? restartLimit,

            Outputs.ServiceDefinitionHealthCheckTcp? tcp,

            int? timeout)
        {
            GracePeriod = gracePeriod;
            Http = http;
            Interval = interval;
            RestartLimit = restartLimit;
            Tcp = tcp;
            Timeout = timeout;
        }
    }
}
