// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Koyeb.Outputs
{

    [OutputType]
    public sealed class ServiceDefinitionHealthCheckTcp
    {
        /// <summary>
        /// The port to use to perform the health check
        /// </summary>
        public readonly int Port;

        [OutputConstructor]
        private ServiceDefinitionHealthCheckTcp(int port)
        {
            Port = port;
        }
    }
}
