// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Koyeb.Outputs
{

    [OutputType]
    public sealed class ServiceDefinitionScaling
    {
        /// <summary>
        /// The maximum number of instance to use to support your service
        /// </summary>
        public readonly int? Max;
        /// <summary>
        /// The minimal number of instances to use to support your service
        /// </summary>
        public readonly int? Min;
        /// <summary>
        /// The regions to apply the scaling configuration
        /// </summary>
        public readonly ImmutableArray<string> Scopes;
        public readonly ImmutableArray<Outputs.ServiceDefinitionScalingTarget> Targets;

        [OutputConstructor]
        private ServiceDefinitionScaling(
            int? max,

            int? min,

            ImmutableArray<string> scopes,

            ImmutableArray<Outputs.ServiceDefinitionScalingTarget> targets)
        {
            Max = max;
            Min = min;
            Scopes = scopes;
            Targets = targets;
        }
    }
}
