// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Koyeb.Inputs
{

    public sealed class KoyebServiceDefinitionGetArgs : Pulumi.ResourceArgs
    {
        [Input("docker")]
        public Input<Inputs.KoyebServiceDefinitionDockerGetArgs>? Docker { get; set; }

        [Input("envs")]
        private InputList<Inputs.KoyebServiceDefinitionEnvGetArgs>? _envs;
        public InputList<Inputs.KoyebServiceDefinitionEnvGetArgs> Envs
        {
            get => _envs ?? (_envs = new InputList<Inputs.KoyebServiceDefinitionEnvGetArgs>());
            set => _envs = value;
        }

        [Input("git")]
        public Input<Inputs.KoyebServiceDefinitionGitGetArgs>? Git { get; set; }

        [Input("instanceTypes", required: true)]
        public Input<Inputs.KoyebServiceDefinitionInstanceTypesGetArgs> InstanceTypes { get; set; } = null!;

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("ports", required: true)]
        private InputList<Inputs.KoyebServiceDefinitionPortGetArgs>? _ports;
        public InputList<Inputs.KoyebServiceDefinitionPortGetArgs> Ports
        {
            get => _ports ?? (_ports = new InputList<Inputs.KoyebServiceDefinitionPortGetArgs>());
            set => _ports = value;
        }

        [Input("regions", required: true)]
        private InputList<string>? _regions;
        public InputList<string> Regions
        {
            get => _regions ?? (_regions = new InputList<string>());
            set => _regions = value;
        }

        [Input("routes")]
        private InputList<Inputs.KoyebServiceDefinitionRouteGetArgs>? _routes;
        public InputList<Inputs.KoyebServiceDefinitionRouteGetArgs> Routes
        {
            get => _routes ?? (_routes = new InputList<Inputs.KoyebServiceDefinitionRouteGetArgs>());
            set => _routes = value;
        }

        [Input("scalings", required: true)]
        public Input<Inputs.KoyebServiceDefinitionScalingsGetArgs> Scalings { get; set; } = null!;

        public KoyebServiceDefinitionGetArgs()
        {
        }
    }
}
