// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Koyeb.Inputs
{

    public sealed class ServiceDefinitionPortArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The internal port on which this service's run command will listen
        /// </summary>
        [Input("port", required: true)]
        public Input<int> Port { get; set; } = null!;

        /// <summary>
        /// The protocol used by your service
        /// </summary>
        [Input("protocol", required: true)]
        public Input<string> Protocol { get; set; } = null!;

        public ServiceDefinitionPortArgs()
        {
        }
        public static new ServiceDefinitionPortArgs Empty => new ServiceDefinitionPortArgs();
    }
}
