// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Koyeb.Inputs
{

    public sealed class ServiceDefinitionGitGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The GitHub branch to deploy
        /// </summary>
        [Input("branch", required: true)]
        public Input<string> Branch { get; set; } = null!;

        [Input("buildpack")]
        public Input<Inputs.ServiceDefinitionGitBuildpackGetArgs>? Buildpack { get; set; }

        [Input("dockerfile")]
        public Input<Inputs.ServiceDefinitionGitDockerfileGetArgs>? Dockerfile { get; set; }

        /// <summary>
        /// If set to true, no Koyeb deployments will be triggered when changes are pushed to the GitHub repository branch
        /// </summary>
        [Input("noDeployOnPush")]
        public Input<bool>? NoDeployOnPush { get; set; }

        /// <summary>
        /// The GitHub repository to deploy
        /// </summary>
        [Input("repository", required: true)]
        public Input<string> Repository { get; set; } = null!;

        /// <summary>
        /// The directory where your source code is located. If not set, the work directory defaults to the root of the repository.
        /// </summary>
        [Input("workdir")]
        public Input<string>? Workdir { get; set; }

        public ServiceDefinitionGitGetArgs()
        {
        }
        public static new ServiceDefinitionGitGetArgs Empty => new ServiceDefinitionGitGetArgs();
    }
}
