// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as koyeb from "@pulumi/koyeb";
 *
 * const my-app = koyeb.getApp({
 *     name: "my-app",
 * });
 * ```
 */
export function getApp(args: GetAppArgs, opts?: pulumi.InvokeOptions): Promise<GetAppResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("koyeb:index/getApp:getApp", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getApp.
 */
export interface GetAppArgs {
    /**
     * The app name
     */
    name: string;
}

/**
 * A collection of values returned by getApp.
 */
export interface GetAppResult {
    /**
     * The date and time of when the app was created
     */
    readonly createdAt: string;
    /**
     * The app domains
     */
    readonly domains: outputs.GetAppDomain[];
    /**
     * The app ID
     */
    readonly id: string;
    /**
     * The app name
     */
    readonly name: string;
    /**
     * The organization ID owning the app
     */
    readonly organizationId: string;
    /**
     * The date and time of when the app was last updated
     */
    readonly updatedAt: string;
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as koyeb from "@pulumi/koyeb";
 *
 * const my-app = koyeb.getApp({
 *     name: "my-app",
 * });
 * ```
 */
export function getAppOutput(args: GetAppOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAppResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("koyeb:index/getApp:getApp", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getApp.
 */
export interface GetAppOutputArgs {
    /**
     * The app name
     */
    name: pulumi.Input<string>;
}
