// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as koyeb from "@pulumi/koyeb";
 *
 * const my_domain = pulumi.output(koyeb.getDomain({
 *     name: "www.exampled.tld",
 * }));
 * ```
 */
export function getDomain(args: GetDomainArgs, opts?: pulumi.InvokeOptions): Promise<GetDomainResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("koyeb:index/getDomain:getDomain", {
        "appName": args.appName,
        "deploymentGroup": args.deploymentGroup,
        "intendedCname": args.intendedCname,
        "messages": args.messages,
        "name": args.name,
        "verifiedAt": args.verifiedAt,
    }, opts);
}

/**
 * A collection of arguments for invoking getDomain.
 */
export interface GetDomainArgs {
    appName?: string;
    deploymentGroup?: string;
    intendedCname?: string;
    messages?: string;
    name: string;
    verifiedAt?: string;
}

/**
 * A collection of values returned by getDomain.
 */
export interface GetDomainResult {
    readonly appName?: string;
    readonly createdAt: string;
    readonly deploymentGroup: string;
    readonly id: string;
    readonly intendedCname: string;
    readonly messages: string;
    readonly name: string;
    readonly organizationId: string;
    readonly status: string;
    readonly type: string;
    readonly updatedAt: string;
    readonly verifiedAt: string;
    readonly version: string;
}

export function getDomainOutput(args: GetDomainOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDomainResult> {
    return pulumi.output(args).apply(a => getDomain(a, opts))
}

/**
 * A collection of arguments for invoking getDomain.
 */
export interface GetDomainOutputArgs {
    appName?: pulumi.Input<string>;
    deploymentGroup?: pulumi.Input<string>;
    intendedCname?: pulumi.Input<string>;
    messages?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    verifiedAt?: pulumi.Input<string>;
}
